### ISSUE TITLE
Start up note

### ISSUE THREAD

**Issue by ghost** [mick88/notepad#5]
When the app starts up it creates a note with "2130837518/1030128! 7f090066! 7f090bb!"

This should be something like, "Write your note here..."

I cannot locate the bit of the code where this comes from.

Also sometimes when you restart the app it creates a few of these messages, in addition to the ones it already remembers, see
![screenshot_2016-01-30-20-43-21](https://cloud.githubusercontent.com/assets/16365833/12698540/0037de9e-c797-11e5-888f-ca801733fd35.png)
![screenshot_2016-01-30-20-43-49](https://cloud.githubusercontent.com/assets/16365833/12698541/003a61fa-c797-11e5-9af7-4ee4198af151.png)

**Comment by gf1721** [comment]
Also sometimes when you restart the app it creates a few of these messages, in addition to the ones it already remembers
